{% set name = "shapash" %}
{% set version = "2.7.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/shapash-{{ version }}.tar.gz
  sha256: 85d91bcd313c2540e732b7838486b58673395155f0c1fd45da3b3f9c4d0bb653

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }},<3.13
    - plotly <6.0.0,>=5.0.0
    - matplotlib-base >=3.2.0
    - numpy <2,>1.18.0
    - pandas >=2.1.0
    - shap >=0.45.0
    - flask >=1.0.4
    - dash >=2.3.1
    - dash-bootstrap-components >=1.1.0
    - dash-core-components >=2.0.0
    - dash-daq >=0.5.0
    - dash-html-components >=2.0.0
    - dash-renderer ==1.8.3
    - dash-table >=5.0.0
    - nbformat >4.2.0
    - numba >=0.53.1
    - scikit-learn <1.6.0,>=1.4.0
    - category_encoders >=2.6.0
    - scipy >=0.19.1
    # This list should be identical to the list in shapash/report/__init__.py
    - ipython
    - nbconvert >=6.0.7
    - papermill >=2.0.0
    - jupyter_client >=7.4.0
    - seaborn >=0.12.2
    - notebook 
    - jinja2 >=2.11.0
    - phik 
    # pip check failure- dash 2.11.1 has requirement Werkzeug<2.3.0, but you have werkzeug 2.3.6.
    - Werkzeug <2.3.0
    # extras_require=extras,
    # - xgboost >=1.0.0
    # - sphinxcontrib-serializinghtml ==1.1.5
    # - sphinxcontrib-qthelp ==1.0.3
    # - sphinxcontrib-jsmath ==1.0.1
    # - sphinxcontrib-htmlhelp ==2.0.0
    # - sphinxcontrib-devhelp ==1.0.2
    # - sphinxcontrib-applehelp ==1.0.2
    # - sphinx_material ==0.0.35
    # - shapash 
    # - ruff 
    # - pytest-cov 
    # - pytest 
    # - pre-commit 
    # - nbsphinx ==0.8.8
    # - mypy 
    # - lime >=0.2.0.0
    # - lightgbm >=2.3.0
    # - catboost >=1.0.1
    # - Sphinx ==4.5.0
    # - Jinja2 >=2.11.0
    # - Flask >=1.0.4
    # - xgboost >=1.0.0
    # - sphinxcontrib-serializinghtml ==1.1.5
    # - sphinxcontrib-qthelp ==1.0.3
    # - sphinxcontrib-jsmath ==1.0.1
    # - sphinxcontrib-htmlhelp ==2.0.0
    # - sphinxcontrib-devhelp ==1.0.2
    # - sphinxcontrib-applehelp ==1.0.2
    # - sphinx_material ==0.0.35
    # - shapash 
    # - ruff 
    # - pytest-cov 
    # - pytest 
    # - pre-commit 
    # - nbsphinx ==0.8.8
    # - mypy 
    # - lime >=0.2.0.0
    # - lightgbm >=2.3.0
    # - catboost >=1.0.1
    # - Sphinx ==4.5.0
    # - Jinja2 >=2.11.0
    # - Flask >=1.0.4
    # - xgboost >=1.0.0
    # - sphinxcontrib-serializinghtml ==1.1.5
    # - sphinxcontrib-qthelp ==1.0.3
    # - sphinxcontrib-jsmath ==1.0.1
    # - sphinxcontrib-htmlhelp ==2.0.0
    # - sphinxcontrib-devhelp ==1.0.2
    # - sphinxcontrib-applehelp ==1.0.2
    # - sphinx_material ==0.0.35
    # - shapash 
    # - ruff 
    # - pytest-cov 
    # - pytest 
    # - pre-commit 
    # - nbsphinx ==0.8.8
    # - mypy 
    # - lime >=0.2.0.0
    # - lightgbm >=2.3.0
    # - catboost >=1.0.1
    # - Sphinx ==4.5.0
    # - Jinja2 >=2.11.0
    # - Flask >=1.0.4
    # - xgboost >=1.0.0
    # - sphinxcontrib-serializinghtml ==1.1.5
    # - sphinxcontrib-qthelp ==1.0.3
    # - sphinxcontrib-jsmath ==1.0.1
    # - sphinxcontrib-htmlhelp ==2.0.0
    # - sphinxcontrib-devhelp ==1.0.2
    # - sphinxcontrib-applehelp ==1.0.2
    # - sphinx_material ==0.0.35
    # - shapash 
    # - ruff 
    # - pytest-cov 
    # - pytest 
    # - pre-commit 
    # - nbsphinx ==0.8.8
    # - mypy 
    # - lime >=0.2.0.0
    # - lightgbm >=2.3.0
    # - catboost >=1.0.1
    # - Sphinx ==4.5.0
    # - Jinja2 >=2.11.0
    # - Flask >=1.0.4
  run_constrained:
    - xgboost >=1.0.0
    - lightgbm >=2.3.0
    - catboost >=1.0.1
    #- acv-exp >=1.2.0
    - lime >=0.2.0.0

test:
  imports:
    - shapash
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MAIF/shapash
  summary: Shapash is a Python library which aims to make machine learning interpretable and understandable by everyone.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
